stages:
  - build
  - test
  - deploy

buildtest-python:
  image: ubuntu:latest
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

unittest-py34:
  image: ubuntu:latest
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - nohup python Main.py &